include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
variables:
  SECURE_ANALYZERS_PREFIX: "${HTL_NEXUS_PROXY}/security-products"
  GRADLE_IMAGE: "${HTL_NEXUS_PROXY}/gradle:8.7.0-jdk21"
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG


stages:
  - build
  - test
  - publish
  - deploy

build app:
  stage: build
  image: "$GRADLE_IMAGE"
  tags:
      - saas-linux-medium-amd64
  script:
      - gradle classes
  rules:
  - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  - if: ($CI_COMMIT_BRANCH == 'main' ||  $CI_COMMIT_BRANCH == 'master')
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && '$CI_MERGE_REQUEST_LABELS =~ /pipeline:deploy/'
  - if: '$CI_MERGE_REQUEST_LABELS =~ /pipeline:jdk21/'
    variables:
        GRADLE_IMAGE: "${HTL_NEXUS_PROXY}/gradle:8.7.0-jdk21"

test app:
  stage: test
  image: "$GRADLE_IMAGE"
  tags:
    - saas-linux-medium-amd64
  script:
    - gradle test
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: ($CI_COMMIT_BRANCH == 'main' ||  $CI_COMMIT_BRANCH == 'master')
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && '$CI_MERGE_REQUEST_LABELS =~ /pipeline:deploy/'
    - if: '$CI_MERGE_REQUEST_LABELS =~ /pipeline:jdk21/'
      variables:
        GRADLE_IMAGE: "${HTL_NEXUS_PROXY}/gradle:8.7.0-jdk21"
# Container for the game module
pre-container-app:
  image: "${HTL_NEXUS_PROXY}/gradle:8.10.2-jdk21"
  stage: build
  tags:
    - saas-linux-medium-amd64
  script:
    - gradle build -x test
  artifacts:
    paths:
      - app/build/libs/titan.jar
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: ($CI_COMMIT_BRANCH == 'main' ||  $CI_COMMIT_BRANCH == 'master')
    - if: $CI_COMMIT_TAG != ""
      when: manual
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && '$CI_MERGE_REQUEST_LABELS =~ /pipeline:deploy/'
    - if: '$CI_MERGE_REQUEST_LABELS =~ /pipeline:jdk21/'
      variables:
        GRADLE_IMAGE: "${HTL_NEXUS_PROXY}/gradle:8.10.2-jdk21"
container-app:
  image: "${HTL_NEXUS_PROXY}/buildah/stable:latest"
  stage: publish
  tags:
    - saas-linux-medium-amd64
  dependencies:
    - "pre-container-app"
  needs:
    - "pre-container-app"
  cache: {}
  script:
    - buildah login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - buildah build -t $IMAGE_TAG -t $CI_REGISTRY_IMAGE:latest -f app/Dockerfile --build-arg JAR_FILE=app/build/libs/titan.jar --build-arg MAPS=worlds/ .
    - buildah push $IMAGE_TAG
    - buildah push $CI_REGISTRY_IMAGE:latest
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: ($CI_COMMIT_BRANCH == 'main' ||  $CI_COMMIT_BRANCH == 'master')
    - if: $CI_COMMIT_TAG != ""
      when: manual
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && '$CI_MERGE_REQUEST_LABELS =~ /pipeline:deploy/'
    - if: '$CI_MERGE_REQUEST_LABELS =~ /pipeline:jdk21/'
      variables:
        GRADLE_IMAGE: "${HTL_NEXUS_PROXY}/gradle:8.10.2-jdk21"

