include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - project: onelitefeather/ci-template
    ref: template
    file: gradle-build.yml
    inputs:
      archivePath: ''

deploy:
  script:
    - gradle publish