include:
  - project: onelitefeather/ci-template
    ref: Better-Pipelines
    file: s3-upload.yaml

variables:
  JAR_FILE: "Titan.jar"
  BUCKET: "olf-dev"
  TEMPLATE: "default"


deploy:
  script:
    - gradle shadowJar
