/**
 * Copyright 2025 OneLiteFeather Network
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package net.onelitefeather.titan.app.architecture;

import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.classes;
import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.noClasses;
import static com.tngtech.archunit.library.dependencies.SlicesRuleDefinition.slices;

import com.tngtech.archunit.base.DescribedPredicate;
import com.tngtech.archunit.core.domain.JavaClass;
import com.tngtech.archunit.core.domain.JavaClasses;
import com.tngtech.archunit.core.domain.JavaMethodCall;
import com.tngtech.archunit.core.domain.JavaModifier;
import com.tngtech.archunit.core.importer.ClassFileImporter;
import com.tngtech.archunit.core.importer.ImportOption;
import com.tngtech.archunit.junit.AnalyzeClasses;
import com.tngtech.archunit.junit.ArchTest;
import com.tngtech.archunit.lang.ArchRule;
import com.tngtech.archunit.lang.conditions.ArchConditions;
import io.avaje.inject.BeanScope;
import io.avaje.inject.PostConstruct;
import io.avaje.inject.spi.Generated;
import jakarta.inject.Singleton;
import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.lang.classfile.Attribute;
import java.lang.classfile.ClassFile;
import java.lang.classfile.ClassModel;
import java.lang.classfile.FieldModel;
import java.lang.classfile.attribute.ConstantValueAttribute;
import java.lang.classfile.constantpool.IntegerEntry;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.OptionalInt;
import java.util.TreeMap;
import net.minestom.server.MinecraftServer;
import net.minestom.server.event.EventNode;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

/**
 * Enforces the feature boundaries: features (protection, spawn, respawn, navigator, sit, tickle,
 * elytra) neither depend on each other nor leak internals, the platform and shared libraries
 * never depend on a feature, and only
 * {@link net.onelitefeather.titan.app.module.FeatureNode} touches the raw Minestom event tree on a
 * feature's behalf.
 *
 * <p><strong>Test sources are not analyzed:</strong> {@link AnalyzeClasses} below is configured
 * with {@link ImportOption.DoNotIncludeTests}, so these rules only check production code under
 * {@code app/src/main}. The test-only template feature under
 * {@code app/src/test/.../feature/example/} (see {@code docs/lobby-modules.md}) is therefore never
 * scanned; it follows the same rules by convention only. A real feature copied from that template
 * into {@code app/src/main} is checked like any other feature.
 */
@AnalyzeClasses(packages = "net.onelitefeather.titan", importOptions = ImportOption.DoNotIncludeTests.class)
class ArchitectureTest {

    private static final String FEATURE_PACKAGE = "net.onelitefeather.titan.app.feature..";
    private static final String MODULE_PACKAGE = "net.onelitefeather.titan.app.module..";
    private static final String COMMON_PACKAGE = "net.onelitefeather.titan.common..";
    private static final String NAVIGATOR_PACKAGE = "net.onelitefeather.titan.app.feature.navigator..";
    private static final String AVAJE_CONFIG_PACKAGE = "io.avaje.config..";
    private static final String BOOTSTRAP_PACKAGE = "net.onelitefeather.titan.app.bootstrap..";

    /**
     * True for a class named {@code *Module}, or a class Avaje Inject's annotation processor
     * generated (e.g. {@code ElytraModule$DI}) - generated wiring code, not hand-authored feature
     * surface. Every feature's own item factory (e.g. {@code NavigatorItems},
     * {@code ElytraLobbyItems}) is package-private, like the rest of a feature's internals: Avaje
     * Inject's generated wiring lives in the same package as the class it annotates, so it never
     * needs a factory itself to be public.
     */
    private static final DescribedPredicate<JavaClass> PUBLIC_FEATURE_API = DescribedPredicate.describe("named '*Module', or generated by Avaje Inject", javaClass -> isModuleType(javaClass) || isAvajeGeneratedType(javaClass));

    /**
     * True for a call to {@code EventNode#addListener}, {@code EventNode#addChild} or
     * {@code MinecraftServer#getGlobalEventHandler()} - the raw Minestom event API a feature must
     * never reach for directly.
     */
    private static final DescribedPredicate<JavaMethodCall> TOUCHES_THE_RAW_EVENT_TREE = DescribedPredicate.describe("calls EventNode#addListener, EventNode#addChild or MinecraftServer#getGlobalEventHandler", ArchitectureTest::touchesTheRawEventTree);

    /**
     * True for a class residing in {@code net.onelitefeather.titan.app.feature..} that declares at
     * least one method annotated with {@link PostConstruct}.
     */
    private static final DescribedPredicate<JavaClass> DECLARES_POST_CONSTRUCT = DescribedPredicate.describe("declares a method annotated with @PostConstruct", javaClass -> javaClass.getMethods().stream().anyMatch(method -> method.isAnnotatedWith(PostConstruct.class)));

    /** Rule 1: a feature must never reach into another feature's package. */
    @ArchTest
    static final ArchRule featureModulesDoNotDependOnEachOther = slices().matching("net.onelitefeather.titan.app.feature.(*)..").should().notDependOnEachOther().because("each feature must stand on its own; anything two features need in common goes through a platform bean or a shared library outside app.feature");

    /** Rule 2: the platform and shared libraries are what features depend on, never the reverse. */
    @ArchTest
    static final ArchRule platformAndCommonDoNotDependOnFeatures = noClasses().that().resideInAnyPackage(MODULE_PACKAGE, COMMON_PACKAGE).should().dependOnClassesThat().resideInAPackage(FEATURE_PACKAGE).because("the platform and shared libraries must stay usable without any particular feature present");

    /**
     * Rule 3: a feature's only declared surface is its {@code *Module} entry point; everything
     * else stays package-private.
     */
    @ArchTest
    static final ArchRule onlyModuleTypesArePublicInFeatures = classes().that().resideInAPackage(FEATURE_PACKAGE).and().haveModifier(JavaModifier.PUBLIC).should(ArchConditions.be(PUBLIC_FEATURE_API)).because("a feature's declared surface is its *Module entry point; everything else must be package-private so it cannot be depended on from outside the feature");

    /**
     * Rule 4: a feature registers a listener only through
     * {@link net.onelitefeather.titan.app.module.FeatureNode}, never the raw Minestom event API
     * directly.
     */
    @ArchTest
    static final ArchRule featuresRegisterListenersOnlyThroughFeatureNode = noClasses().that().resideInAPackage(FEATURE_PACKAGE).should().callMethodWhere(TOUCHES_THE_RAW_EVENT_TREE).because("a feature registers through FeatureNode instead of the raw event API directly, which guarantees cleanup and error attribution on stop()");

    /**
     * Rule 5: a class in {@code app.feature} that declares an {@code @PostConstruct} method must
     * also be a {@code @Singleton} bean, or Avaje Inject never discovers it.
     */
    @ArchTest
    static final ArchRule classesWithPostConstructInFeaturesAreSingleton = classes().that(DECLARES_POST_CONSTRUCT).should().beAnnotatedWith(Singleton.class).because("a class under app.feature with an @PostConstruct method is only built and started by Avaje Inject if it is also a @Singleton bean; missing the annotation would make the feature vanish silently instead of failing the build");

    /**
     * Rule 6: a feature is built through constructor injection only, never by reaching into the
     * {@link BeanScope} itself.
     */
    @ArchTest
    static final ArchRule featureModulesDoNotUseBeanScope = noClasses().that().resideInAPackage(FEATURE_PACKAGE).should().dependOnClassesThat().areAssignableTo(BeanScope.class).because("a feature must ask for its dependencies through its constructor, never look them up itself via BeanScope, which is the service-locator pattern dependency injection is meant to replace");

    /**
     * Rule 7: two features sharing an {@code EVENT_PRIORITY} value would make the order in which
     * they process the same event depend on an undocumented tie-break instead of a deterministic
     * one. Plain bytecode inspection rather than an {@code ArchRule}, because ArchUnit has no
     * built-in "static field values are unique across a set of classes" condition; scanning is
     * done here, once, with
     * {@link ClassFileImporter} rather than relying on the class-level {@link AnalyzeClasses}
     * cache, so this method stays independent of the other rules in this class (F.I.R.S.T.).
     *
     * <p>Reads {@code EVENT_PRIORITY}'s value straight from the field's {@code ConstantValue}
     * bytecode attribute via the built-in {@link ClassFile} API (Java 25), instead of
     * {@code java.lang.reflect.Field#getInt}: reflectively reading a static field - even a
     * compile-time constant one - forces the JVM to initialize its declaring class first. For a
     * feature whose static initializer builds an {@code ItemStack} (e.g. {@code NavigatorModule}),
     * that would fail outside a running Minestom server, and would permanently poison the class for
     * every later test in the same JVM. Reading the constant from the class file bytes never loads
     * or initializes the class at all.
     */
    @Test
    void eventPriorityValuesAreUniqueAcrossFeatures() {
        JavaClasses classes = new ClassFileImporter().withImportOption(new ImportOption.DoNotIncludeTests()).importPackages("net.onelitefeather.titan.app.feature");
        Map<Integer, List<String>> classNamesByPriority = new TreeMap<>();
        for (JavaClass javaClass : classes) {
            eventPriorityOf(javaClass).ifPresent(priority -> classNamesByPriority.computeIfAbsent(priority, unused -> new ArrayList<>()).add(javaClass.getSimpleName()));
        }
        List<String> duplicates = classNamesByPriority.entrySet().stream().filter(entry -> entry.getValue().size() > 1).map(entry -> entry.getKey() + ": " + entry.getValue()).toList();
        Assertions.assertTrue(duplicates.isEmpty(), "EVENT_PRIORITY values must be unique across every feature in app.feature, but found duplicates naming both: " + duplicates);
    }

    /**
     * @param javaClass a class found in {@code net.onelitefeather.titan.app.feature}
     * @return the {@code int} value of {@code javaClass}'s own {@code EVENT_PRIORITY} field, read
     *         from its class file's {@code ConstantValue} attribute, or empty if it declares none
     */
    private static OptionalInt eventPriorityOf(JavaClass javaClass) {
        String resourceName = javaClass.getName().replace('.', '/') + ".class";
        try (InputStream classBytes = ArchitectureTest.class.getClassLoader().getResourceAsStream(resourceName)) {
            if (classBytes == null) {
                return OptionalInt.empty();
            }
            ClassModel classModel = ClassFile.of().parse(classBytes.readAllBytes());
            for (FieldModel field : classModel.fields()) {
                if (!"EVENT_PRIORITY".equals(field.fieldName().stringValue())) {
                    continue;
                }
                for (Attribute<?> attribute : field.attributes()) {
                    if (attribute instanceof ConstantValueAttribute constantValue && constantValue.constant() instanceof IntegerEntry integerEntry) {
                        return OptionalInt.of(integerEntry.intValue());
                    }
                }
            }
            return OptionalInt.empty();
        } catch (IOException exception) {
            throw new UncheckedIOException("Unable to read the class file for " + javaClass.getName(), exception);
        }
    }

    /**
     * Rule 8: the navigator's destinations are fixed in code, not read from the
     * {@code io.avaje.config} facade.
     */
    @ArchTest
    static final ArchRule navigatorDoesNotDependOnAvajeConfig = noClasses().that().resideInAPackage(NAVIGATOR_PACKAGE).should().dependOnClassesThat().resideInAPackage(AVAJE_CONFIG_PACKAGE).because("the navigator's title and destinations are fixed in NavigatorModule/Destination, not read from configuration");

    /**
     * Rule 9: the platform ({@code app.module}) must not depend on the composition root
     * ({@code app.bootstrap}).
     */
    @ArchTest
    static final ArchRule platformDoesNotDependOnCompositionRoot = noClasses().that().resideInAPackage(MODULE_PACKAGE).should().dependOnClassesThat().resideInAPackage(BOOTSTRAP_PACKAGE).because("app.bootstrap wires platform beans from app.module types, never the reverse; a dependency back into app.bootstrap would create a package cycle");

    ArchitectureTest() {
    }

    private static boolean touchesTheRawEventTree(JavaMethodCall call) {
        JavaClass owner = call.getTargetOwner();
        String methodName = call.getTarget().getName();
        boolean onEventNode = owner.isAssignableTo(EventNode.class) && ("addListener".equals(methodName) || "addChild".equals(methodName));
        boolean globalHandlerLookup = owner.isEquivalentTo(MinecraftServer.class) && "getGlobalEventHandler".equals(methodName);
        return onEventNode || globalHandlerLookup;
    }

    private static boolean isAvajeGeneratedType(JavaClass javaClass) {
        // getName() (the fully qualified binary name), not getSimpleName(): ArchUnit parses a
        // "$"-containing binary name as if it always denoted a nested class, so for Avaje
        // Inject's generated top-level "FooModule$DI" class, getSimpleName() returns just "DI",
        // not "FooModule$DI" - matching on it here would be far too broad (any class simply
        // named "DI" anywhere). getName() is the full binary name and is not subject to that
        // parsing.
        return javaClass.getName().endsWith("$DI") && javaClass.isAnnotatedWith(Generated.class);
    }

    private static boolean isModuleType(JavaClass javaClass) {
        return javaClass.getSimpleName().endsWith("Module");
    }
}
