/**
 * Copyright 2025 OneLiteFeather Network
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package net.onelitefeather.titan.app.architecture;

import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.classes;
import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.noClasses;
import static com.tngtech.archunit.library.dependencies.SlicesRuleDefinition.slices;

import com.tngtech.archunit.base.DescribedPredicate;
import com.tngtech.archunit.core.domain.JavaClass;
import com.tngtech.archunit.core.domain.JavaMethodCall;
import com.tngtech.archunit.core.domain.JavaModifier;
import com.tngtech.archunit.core.importer.ImportOption;
import com.tngtech.archunit.junit.AnalyzeClasses;
import com.tngtech.archunit.junit.ArchTest;
import com.tngtech.archunit.lang.ArchRule;
import com.tngtech.archunit.lang.conditions.ArchConditions;
import io.avaje.inject.BeanScope;
import io.avaje.inject.PostConstruct;
import io.avaje.inject.spi.Generated;
import jakarta.inject.Singleton;
import net.minestom.server.MinecraftServer;
import net.minestom.server.event.EventNode;

/**
 * Enforces the feature boundaries between {@code app.feature}, the platform and shared libraries.
 *
 * <p>{@link AnalyzeClasses} below excludes test sources ({@link ImportOption.DoNotIncludeTests}),
 * so these rules only check {@code app/src/main}; the test-only template feature under
 * {@code feature/example/} follows them only by convention.
 */
@AnalyzeClasses(packages = "net.onelitefeather.titan", importOptions = ImportOption.DoNotIncludeTests.class)
class ArchitectureTest {

    private static final String FEATURE_PACKAGE = "net.onelitefeather.titan.app.feature..";
    private static final String MODULE_PACKAGE = "net.onelitefeather.titan.app.module..";
    private static final String COMMON_PACKAGE = "net.onelitefeather.titan.common..";
    private static final String NAVIGATOR_PACKAGE = "net.onelitefeather.titan.app.feature.navigator..";
    private static final String AVAJE_CONFIG_PACKAGE = "io.avaje.config..";
    private static final String BOOTSTRAP_PACKAGE = "net.onelitefeather.titan.app.bootstrap..";

    /**
     * True for a class named {@code *Module}, or one Avaje Inject's annotation processor generated.
     */
    private static final DescribedPredicate<JavaClass> PUBLIC_FEATURE_API = DescribedPredicate.describe("named '*Module', or generated by Avaje Inject", javaClass -> isModuleType(javaClass) || isAvajeGeneratedType(javaClass));

    /** True for a call to the raw Minestom event API a feature must never reach for directly. */
    private static final DescribedPredicate<JavaMethodCall> TOUCHES_THE_RAW_EVENT_TREE = DescribedPredicate.describe("calls EventNode#addListener, EventNode#addChild or MinecraftServer#getGlobalEventHandler", ArchitectureTest::touchesTheRawEventTree);

    /**
     * True for a class in {@code app.feature..} that declares a method annotated with
     * {@link PostConstruct}.
     */
    private static final DescribedPredicate<JavaClass> DECLARES_POST_CONSTRUCT = DescribedPredicate.describe("declares a method annotated with @PostConstruct", javaClass -> javaClass.getMethods().stream().anyMatch(method -> method.isAnnotatedWith(PostConstruct.class)));

    /** Rule 1: a feature must never reach into another feature's package. */
    @ArchTest
    static final ArchRule featureModulesDoNotDependOnEachOther = slices().matching("net.onelitefeather.titan.app.feature.(*)..").should().notDependOnEachOther().because("a feature must never depend on another feature's package directly");

    /** Rule 2: the platform and shared libraries are what features depend on, never the reverse. */
    @ArchTest
    static final ArchRule platformAndCommonDoNotDependOnFeatures = noClasses().that().resideInAnyPackage(MODULE_PACKAGE, COMMON_PACKAGE).should().dependOnClassesThat().resideInAPackage(FEATURE_PACKAGE).because("the platform and shared libraries must stay usable without any particular feature present");

    /** Rule 3: a feature's only declared surface is its {@code *Module} entry point. */
    @ArchTest
    static final ArchRule onlyModuleTypesArePublicInFeatures = classes().that().resideInAPackage(FEATURE_PACKAGE).and().haveModifier(JavaModifier.PUBLIC).should(ArchConditions.be(PUBLIC_FEATURE_API)).because("only a feature's *Module entry point may be public");

    /**
     * Rule 4: a feature registers a listener only through
     * {@link net.onelitefeather.titan.core.module.FeatureNode}.
     */
    @ArchTest
    static final ArchRule featuresRegisterListenersOnlyThroughFeatureNode = noClasses().that().resideInAPackage(FEATURE_PACKAGE).should().callMethodWhere(TOUCHES_THE_RAW_EVENT_TREE).because("a feature must register listeners through FeatureNode, not the raw event API");

    /**
     * Rule 5: a class with an {@code @PostConstruct} method in {@code app.feature} must also be a
     * {@code @Singleton} bean.
     */
    @ArchTest
    static final ArchRule classesWithPostConstructInFeaturesAreSingleton = classes().that(DECLARES_POST_CONSTRUCT).should().beAnnotatedWith(Singleton.class).because("a class with an @PostConstruct method must also be a @Singleton bean, or Avaje Inject never discovers it");

    /**
     * Rule 6: a feature is built through constructor injection only, never via {@link BeanScope}.
     */
    @ArchTest
    static final ArchRule featureModulesDoNotUseBeanScope = noClasses().that().resideInAPackage(FEATURE_PACKAGE).should().dependOnClassesThat().areAssignableTo(BeanScope.class).because("a feature must get its dependencies through its constructor, never via BeanScope");

    /**
     * Rule 8: the navigator's destinations are fixed in code, not read from the
     * {@code io.avaje.config} facade.
     */
    @ArchTest
    static final ArchRule navigatorDoesNotDependOnAvajeConfig = noClasses().that().resideInAPackage(NAVIGATOR_PACKAGE).should().dependOnClassesThat().resideInAPackage(AVAJE_CONFIG_PACKAGE).because("the navigator's destinations are fixed in code, not read from configuration");

    /**
     * Rule 9: the platform ({@code app.module}) must not depend on the composition root
     * ({@code app.bootstrap}).
     */
    @ArchTest
    static final ArchRule platformDoesNotDependOnCompositionRoot = noClasses().that().resideInAPackage(MODULE_PACKAGE).should().dependOnClassesThat().resideInAPackage(BOOTSTRAP_PACKAGE).because("app.bootstrap depends on app.module types, never the reverse");

    ArchitectureTest() {
    }

    private static boolean touchesTheRawEventTree(JavaMethodCall call) {
        JavaClass owner = call.getTargetOwner();
        String methodName = call.getTarget().getName();
        boolean onEventNode = owner.isAssignableTo(EventNode.class) && ("addListener".equals(methodName) || "addChild".equals(methodName));
        boolean globalHandlerLookup = owner.isEquivalentTo(MinecraftServer.class) && "getGlobalEventHandler".equals(methodName);
        return onEventNode || globalHandlerLookup;
    }

    private static boolean isAvajeGeneratedType(JavaClass javaClass) {
        // getName() (full binary name), not getSimpleName(): ArchUnit treats "$" as a nested
        // class, so getSimpleName() on "FooModule$DI" returns just "DI" - too broad a match.
        return javaClass.getName().endsWith("$DI") && javaClass.isAnnotatedWith(Generated.class);
    }

    private static boolean isModuleType(JavaClass javaClass) {
        return javaClass.getSimpleName().endsWith("Module");
    }
}
