metadata.format.version = "1.1"

[versions]
# Paper
paper = "1.18.2-R0.1-SNAPSHOT"

[libraries]

# Paper
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
[bundles]

[plugins]
