name: Main Branch Build

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    if: github.repository_owner == 'OneLiteFeatherNET'
    name: Build
    runs-on: ubuntu-latest
    env:
      ONELITEFEATHER_MAVEN_USERNAME: ${{ secrets.ONELITEFEATHER_MAVEN_USERNAME }}
      ONELITEFEATHER_MAVEN_PASSWORD: ${{ secrets.ONELITEFEATHER_MAVEN_PASSWORD }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 23
      - name: Test
        run: ./gradlew test
      - name: Publish
        run: ./gradlew publish